### ISSUE TITLE
Make it compatible with PDI 6

### ISSUE THREAD

**Issue by cvagner** [atolcd/pentaho-gis-plugins#7]

**Comment by tsykes** [comment]
Hi. Is this update done? I still see issues with this plugin in PDI 6. Mostly seem to be around vfs commons 1 vs vfs2.

**Comment by evanvugt** [comment]
It has been almost a year since the last code edits. Is an updated version of the plugin for PDI 6.x coming soon?

**Comment by tsykes** [comment]
I updated the project to make compatible with PDI 6. It works on my laptop. I can do a pull request with the changes. Can the atolcd guys update the marketplace then? I don't really know how to do that.

**Comment by julianobn** [comment]
@tsykes Thank you for updating it. I'm trying to install your fork in order to get that vfs error corrected, but I'm not an experienced Maven user. After `mvn install` I got success at `concave-hull`, `dxf`, `geojson`, `MIF MID`, `shp` and `spatialite` modules, but error on `Pentaho's Data Integrator GIS Plugins` (`Pentaho's Data Integrator GIS Plugins and modified deps` is skipped). I'm getting also this error:

`[ERROR] Failed to execute goal on project pentaho-gis-plugins: Could not resolve dependencies for project com.atolcd.pentaho.di:pentaho-gis-plugins:jar:1.1-SNAPSHOT: The following artifacts could not be resolved: oracle:sdoapi:jar:11.2.0, oracle:sdoutl:jar:11.2.0: Failure to find oracle:sdoapi:jar:11.2.0 in file:///home/juliano/data-integration/plugins/steps/pentaho-gis-plugins-master/pentaho-gis-plugins/../local-maven-repo was cached in the local repository, resolution will not be reattempted until the update interval of local-maven-repo has elapsed or updates are forced -> [Help 1]`

Could you help me telling what I'm supposed to do to generate the plugin jar correcty?
Thank you!

**Comment by julianobn** [comment]
@tsykes Okay, now I've found your compiled jar file -- thank you for the fix.
For everybody who have found this Issue, download the jar file here `https://github.com/tsykes/pentaho-gis-plugins/releases`, install official AtolCD plugin via Pentaho Marketplace, quit PDI and copy the jar into `plugins/steps/pentaho-gis-plugins` directory.

**Comment by tsykes** [comment]
Hi. The reason that it doesn't build is that it's missing some
dependencies. The oracle jars and I think a couple others were missing. Not
sure exactly which ones because I did this on a computer I'm not using
anymore. I didn't look very hard but didn't find a way to include the
oracle jars in maven which might be why they weren't there in the first
place. I manually downloaded the missing dependencies. Then it built fine.

Need to get it updated in the Pentaho Marketplace though and probably needs
some maintenance for PDI 7.

Todd

**Comment by tsykes** [comment]
Julian, you can ping me offline at toddsykes at gmail and maybe we can work together to get Marketplace updated properly.

**Comment by julianobn** [comment]
@tsykes Good! I'm at work now, my email is juliano.bn at gmail.

**Comment by cvagner** [comment]
Thanks @tsykes. It is now compatible with PDI 5, 6 and 7.
